noNamespace:
  - rehype-jargon
  - rehype-highlight-lines
customBuild:
  - i18n
  - new-design
  - prettier-config
  - plugin-bundle
  - rehype-jargon
  - rehype-highlight-lines
skipTests:
  - theo
packageJson:
  backend:
    name: backend.freesewing.org
  aimee:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  basicsleeve:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  bee:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  beltloops:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  benjamin:
    author: woutervdub (https://github.com/woutervdub)
  billy:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  boxpleatpocket:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  byron:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  code:
    c8:
      reporter: html
      all: yes
      extension: mjs
      exclude:
        - 'node_modules/*'
        - 'tests'
  calanthe:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  camden:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  capsleeve:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  claude:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  daisy:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  dalton:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  fallon:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  hi:
    author: woutervdub (https://github.com/woutervdub)
  holmes:
    author: AlfaLyr (https://github.com/alfalyr)
  inseampocket:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  i18n:
    private: true
  jackson:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  lucy:
    author: SeaZeeZee (https://github.com/SeaZeeZee)
  lunetius: &starf
    author: Starfetch (https://github.com/starfetch)
  magde:
    author: clegganator259 (https://github.com/clegganator259)
  new-design:
    exports: '!'
    bin:
      new-design: './index.mjs'
    files:
      - README.md
      - package.json
      - lib/**/*
      - shared/**/*
      - templates/**/*
      - index.mjs
      - package.json
    module: '!'
  noble:
    author: woutervdub (https://github.com/woutervdub)
  octoplushy:
    author: woutervdub (https://github.com/woutervdub)
  patchpocket:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  peach:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  pearpocket:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  plugin-gore:
    author: AlfaLyr (https://github.com/alfalyr)
  plugin-logorg:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  prettier-config:
    type: 'module'
    exports: { .: './index.json' }
    scripts: { build: 'echo "prettier-config: No build required" && exit 0' }
    keywords:
      - prettier
    files:
      - index.json
      - package.json
  rehype-hightlight-lines:
    private: true
    rufflebutterflysleeve:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)   
  sandy:
    author: AlfaLyr (https://github.com/alfalyr)
  scarlett:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)  
  sleevecap:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)   
  spreadsleeve:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)   
  theobald:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)   
  tiberius: *starf
  unice:
    author: Anna Puk (https://github.com/anna-puk)
  ursula:
    author: Natalia Sayang (https://github.com/nataliasayang)
  waistbandcurved:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd) 
  waistbandstraight:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)  
  waralee:
    author: woutervdub (https://github.com/woutervdub)
  walburga: *starf
  wanda:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)  
  watchpocket:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)  
  weltpocket:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)  
  yuri:
    author: biou (https://github.com/biou)
